"""
Annalist class for processing a FieldValueMap in an annalist view value mapping table.

A FieldValueMap accepts a context field identifier and a field description structure,
and generates context values to drive rendering of that field in a form.
The template used is expected to iterate over the fields and render each one, e.g.:

    {% for field in fields %}
    {% include field.field_render_edit %}
    {% endfor %}

The iterated values of `field` provide additional values for the field rendering template,
including the value of the entity field to be presented.  Field descriptions are bound 
to entity values as the context elements are generated by this class. 

Entity and form field names used for this value are obtained from the field definition;
i.e. they are defined indirectly to support data-driven form generation.
"""

__author__      = "Graham Klyne (GK@ACM.ORG)"
__copyright__   = "Copyright 2014, G. Klyne"
__license__     = "MIT (http://opensource.org/licenses/MIT)"

import logging
log = logging.getLogger(__name__)

import collections

from django.conf                    import settings

from annalist.fields.render_utils   import bound_field

# Named tuple is base class for FieldValueMap:
# @@TODO: get rid of this and use simple constructor
_FieldValueMap_tuple = collections.namedtuple("FieldValueMap", ("c", "f"))

class FieldValueMap(_FieldValueMap_tuple):
    """
    Define an entry in an entity value mapping table corresponding to a
    field value and description, which is added to a list of such fields
    in the indicated context variable.

    NOTE: select fields are handled by having a special field 'options' passed
    in the default value supplied, which is picked out and handled specially
    in the bound_field class.

    c       request context field name for the field values
    f       field description structure (cf. `FieldDescription`)

    NOTE: The form rendering template iterates over the context field values to be 
    added to the form display.  The constructor for this object appends the current
    field to a list of field value mappings at the indcated context field.
    """

    def __new__(cls, *args, **kwargs):
        self = super(FieldValueMap, cls).__new__(cls, *args, **kwargs)
        self.e = self.f['field_property_uri']
        self.i = self.f['field_name']
        return self

    def _map_to_context(self, vals, valkey, extras):
        """
        Returns a dictionary of values to be added to the display context under construction
        """
        subcontext = {}
        if self.c:
            options = ["(no options)"]
            options_key = self.f.get('field_options', None)
            if options_key:
                if extras and options_key in extras:
                    options = extras[options_key]
                else:
                    options = ['(missing options)']
            boundfield = bound_field(
                field_description=self.f, 
                entity=vals, key=valkey,
                options=options,
                extras=extras
                )
            subcontext[self.c] = boundfield
        return subcontext

    def map_entity_to_context(self, entityvals, extras=None):
        return self._map_to_context(entityvals, self.e, extras)

    def map_form_to_context(self, formvals, extras=None):
        # @@TODO: repeats entity value logic; candidate for removal by handling all context 
        #         regeneration via entity values
        return self._map_to_context(formvals, self.i, extras)

    def map_form_to_entity(self, formvals):
        entityvals = {}
        if self.e:
            log.debug("FieldValueMap.map_form_to_entity %s, %r"%(self.e, formvals))
            v = formvals.get(self.i, None)
            if v:
                entityvals[self.e] = v
        return entityvals

    def map_form_to_entity_repeated_item(self, formvals, prefix):
        """
        Extra helper method used when mapping repeated field items to repeated entity values.
        The field name extracted is constructed using the supplied prefix string.

        Returns None if the prefixed value does not exist, which may be used as a loop
        termination condition.
        """
        # log.info("Form->entity: prefix %s, fieldname %s"%(prefix, self.i))
        v = formvals.get(prefix+self.i, None)
        if v:
            return {self.e: v}
        return None

    def map_form_to_context_repeated_item(self, formvals, prefix):
        """
        Extra helper method used when mapping repeated field items to repeated context values.
        The field name extracted is constructed using the supplied prefix string.

        Returns None if the prefixed value does not exist, which may be used as a loop
        termination condition.
        """
        # @@TODO: repeats entity value logic; candidate for removal by handling all context 
        #         regeneration via entity values
        # log.info("Form->entity: prefix %s, fieldname %s"%(prefix, self.i))
        v = formvals.get(prefix+self.i, None)
        if v:
            return bound_field(
                field_description=self.f, 
                entity={self.i: v}, key=self.i,
                options=[], extras={}
                )
        return None

# End.